### ISSUE TITLE
Remove `Recommends: xclip`?

### ISSUE THREAD

**Issue by elcste** [barnumbirr/alacritty-debian#2]
First, thanks for building these packages! I was missing the upstream-provided ones.

Since Alacritty changed its x11 clipboard with https://github.com/alacritty/alacritty/pull/2207, I think the package doesn't need `Recommends: xclip`. What do you think?

It's easy enough to skip with `--no-install-recommends`, but sometimes I forget when installing a new machine.

**Comment by barnumbirr** [comment]
Thanks for the report, nice catch 💪 
Fixed in [v0.7.2-2](https://github.com/barnumbirr/alacritty-debian/releases/tag/v0.7.2-2).
