### ISSUE TITLE
not an issue !

### ISSUE THREAD

**Issue by okalm** [barnumbirr/alacritty-debian#5]
Hi there, 
Sorry for this since there is literally zero problem, but I just want to say thank you for the work done with this package and also for i3blocks-debian too !!
Both work without an issue, so very well done mate you did good.
May be you could ask to be maintainer at the Debian project at least for those packages(of course if you have enough time), for the community it can't be worst than having a 2015 outdated i3blocks and they will certainly appreciate to install alacritty instead of kitty.
Anyway thank you again and stay safe :-)

**Comment by barnumbirr** [comment]
Hello there,
thank you for the kind words, much appreciated.

I could indeed look to get `i3blocks` updated, shouldn't take much work.

`alacritty` on the other hand is a whole other can of worms as all underlying dependencies need to be packaged up as crates first (which is one of the reasons I started to package it myself, without following Debian packaging rules). You can track the progress here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851639

Cheers!
